name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env: # 環境変数の定義
      BRANCH: main
      OVERRIDE: take one
      ACTOR: ${{ github.actor }}
    steps:
      - run: echo "${{ env.BRANCH }}" # 環境変数の参照
      - uses: actions/checkout@v4
        with: 
          ref: ${{ env.BRANCH }}
      - env: # 環境変数の上書き
          OVERRIDE: take two
        run: echo "${{ env.OVERRIDE }}"
      - run: echo "$GITHUB_ACTOR" # GitHub提供の環境変数の参照
      - run: echo "${{ github.action }}" # GitHub提供の環境変数の参照
      - run: echo "${{ github.actor }}" # GitHub提供の環境変数の参照
      